// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmfxglbwiktplgzjzjub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tZnhnbGJ3aWt0cGxnemp6anViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyODYxNjAsImV4cCI6MjA1Mzg2MjE2MH0.k8DS1zuKPc83K8rKhC7AFIrOYgm2yJ4UZOFaEaqOxpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);